export type endpoints =
  | "ammos"
  | "armors"
  | "ashes"
  | "bosses"
  | "classes"
  | "creatures"
  | "incantations"
  | "items"
  | "locations"
  | "npcs"
  | "shields"
  | "sorceries"
  | "spirits"
  | "talismans"
  | "weapons";